module.exports=
{
    Programming: [
        {
          title: "Mern Stack Development",
          instructor: "Ms. Ashwini",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjUG1q1NO6Ef5p9OwZqTEMtqPSWGkwFzpjig&s",
          description: "Learn full-stack web development using MongoDB, Express.js, React, and Node.js in this comprehensive course.",
          video: "https://www.youtube.com/watch?v=CvCiNeLnZ00", // URL to a demo or introductory video
        },
        {
          title: "Data Science",
          instructor: "Mr. Vinoth",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpRY6ZRTxTGqZNYzHJuQKDqPZoXEs53ZtVsA&s",
          description: "Master data science with Python, machine learning, and data visualization tools.",
          video: "https://www.youtube.com/data-science-video",
        },
        {
          title: "Web Development Using WordPress",
          instructor: "Mr. Krithik",
          image: "https://cloudfront.entri.app/media/pack_thumbnails/2022/03/30/web-development-using-wordpress-01_1.png",
          description: "Build powerful websites using WordPress, from beginner to advanced techniques.",
          video: "https://www.youtube.com/wordpress-video",
        },
        {
          title: "Data Analytics | Tamil",
          instructor: "Ms. Sanjana",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0ilmGbrSYrwnEU4_n8W3nATKeZCbLeCXReA&s",
          description: "Understand data analytics concepts and tools to analyze business data effectively, taught in Tamil.",
          video: "https://www.youtube.com/data-analytics-video",
        },
      ],
      LanguageLearning: [
        {
          title: "English - தமிழ்",
          instructor: "Ms. Thilaga",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRw0Mr41gbQmpmT2Y1PolUHKteixXFPpdLQCw&s",
          description: "Learn English through Tamil with easy-to-follow lessons and practical exercises.",
          video: "https://www.youtube.com/english-tamil-video",
        },
        {
          title: "Tamil to English Fluency Program",
          instructor: "Swetha",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRo6Wvw5ux_qE6MiaAMp2KCyGbU_1RYlvwVrA&s",
          description: "Become fluent in English from Tamil with a structured language-learning path.",
          video: "https://www.youtube.com/tamil-to-english-video",
        },
        {
          title: "Employability and Placement Training",
          instructor: "Joy",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjOLnfa1PLRp8BX5gEiOq2VBQ1-01mDGBqGg&s",
          description: "Prepare for the job market with comprehensive employability skills and interview training.",
          video: "https://www.youtube.com/employability-training-video",
        },
        {
          title: "AI Tutorial",
          instructor: "AI",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIJwZK5iMjbA8TMbI5FbCpCdJp9gIVWH2XDg&s",
          description: "Learn Artificial Intelligence concepts and applications with easy tutorials.",
          video: "https://www.youtube.com/ai-tutorial-video",
        },
      ],
      CodingDevelopment: [
        {
          title: "Data Science and Machine Learning",
          instructor: "AVL Hub",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRypzF5US55MoJm77OnJxNdGAp9_oL8Ak3vlw&s",
          description: "Explore data science and machine learning techniques for real-world applications.",
          video: "https://www.youtube.com/data-science-ml-video",
        },
        {
          title: "Full-Stack Web Development",
          instructor: "AVL Hub",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjUG1q1NO6Ef5p9OwZqTEMtqPSWGkwFzpjig&s",
          description: "Learn front-end and back-end web development from scratch using modern technologies.",
          video: "https://www.youtube.com/full-stack-web-video",
        },
        {
          title: "Web Development Using WordPress",
          instructor: "AVL Hub",
          image: "https://cloudfront.entri.app/media/pack_thumbnails/2022/03/30/web-development-using-wordpress-01_1.png",
          description: "Master WordPress web development to create custom websites and blogs.",
          video: "https://www.youtube.com/wordpress-video-2",
        },
        {
          title: "React Native Development",
          instructor: "AVL Hub",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFgcXvwt7_XfsK3os99JTAXuaEtpwoM1uDQA&s",
          description: "Develop cross-platform mobile applications using React Native.",
          video: "https://www.youtube.com/react-native-video",
        },
      ],
      TradingPersonalFinance: [
        {
          title: "Stock Market 360",
          instructor: "Shanthi",
          image: "https://cloudfront.entri.app/media/pack_thumbnails/2023/08/22/Stock-Market-360-01.png",
          description: "A complete guide to stock market trading, from basics to advanced strategies.",
          video: "https://www.youtube.com/stock-market-360-video",
        },
        {
          title: "Investment Essentials: 2-Day Live Workshop",
          instructor: "Nagaraj",
          image: "https://cloudfront.entri.app/media/pack_thumbnails/2024/12/31/Investment_Essentials.png",
          description: "Join a live 2-day workshop on the fundamentals of investing.",
          video: "https://www.youtube.com/investment-essentials-video",
        },
        {
          title: "Stock Market Integrated Course - Tamil",
          instructor: "Nagaraj",
          image: "https://cloudfront.entri.app/media/pack_thumbnails/2024/07/01/Stock-Market-Integrated-Course-01.png",
          description: "Learn stock market techniques in Tamil with this comprehensive course.",
          video: "https://www.youtube.com/stock-market-integrated-video",
        },
        {
          title: "Stock Market Basics",
          instructor: "Nagaraj",
          image: "https://cloudfront.entri.app/media/pack_thumbnails/2024/12/02/Stock_market__Basic0_1.png",
          description: "Understand the basics of stock market investing with this introductory course.",
          video: "https://www.youtube.com/stock-market-basics-video",
        },
      ],
      CommerceAccounting: [
        {
          title: "SAP Material Management",
          instructor: "AVL Hub",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQur-nyclG8TcS7Gc9mjZ1XuBxgpAfyzxkYVQ&s",
          description: "Learn the fundamentals of SAP Material Management for effective business operations.",
          video: "https://www.youtube.com/sap-material-management-video",
        },
        {
          title: "PwC Certified Tax Professional - Tamil",
          instructor: "PwC",
          image: "https://cloudfront.entri.app/media/pack_thumbnails/2024/07/09/PwC_Certified_Tax_Professional_01.png",
          description: "Get certified as a tax professional by PwC, with training in Tamil.",
          video: "https://www.youtube.com/pwc-tax-professional-video",
        },
        {
          title: "Tally Essential",
          instructor: "Santhosh",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZvMFtFY8UCDFryqfPSXDh69DPPU3yqKEwfw&s",
          description: "Master Tally for accounting and business management tasks.",
          video: "https://www.youtube.com/tally-essential-video",
        },
        {
          title: "SAP Finance & Controlling - Tamil",
          instructor: "AVL Hub",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZetQoSow47msOqE1vcaVNIBrchkxcuso4mg&s",
          description: "Learn SAP Finance and Controlling concepts for efficient business management.",
          video: "https://www.youtube.com/sap-finance-video",
        },
      ],
      EngineeringUpskilling: [
        {
          title: "Quantity Surveying Tamil",
          instructor: "Janagi",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP98KugcJNxg_GfXxW23E7QPJR9L1BUVmsyA&s",
          description: "Learn quantity surveying techniques and principles in Tamil.",
          video: "https://www.youtube.com/quantity-surveying-video",
        },
        {
          title: "AutoCAD Training Tamil",
          instructor: "Arun",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ06sdmp5Qb5vq3KRF6TkF3GP6Cbk5VtO4MHQ&s",
          description: "Learn AutoCAD for engineering design and drafting in Tamil.",
          video: "https://www.youtube.com/autocad-training-video",
        },
        {
          title: "Civil Engineering Project Management",
          instructor: "Karthik",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZFtV-T-UK24MfBGdXSbcEnrs1rFQGBKSKXg&s",
          description: "Get trained in civil engineering project management techniques.",
          video: "https://www.youtube.com/civil-engineering-video",
        },
      ],
      CareerDevelopment: [
        {
          title: "Campus to Corporate",
          instructor: "Mr. Vengat",
          image: "https://cloudfront.entri.app/media/pack_thumbnails/2024/12/18/caree_development.png",
          description: "Prepare for the transition from campus to corporate life with essential soft skills.",
          video: "https://www.youtube.com/campus-to-corporate-video",
        },
      ],
      SalesMarketing: [
        {
          title: "Digital Marketing",
          instructor: "Sidin Vadukut",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAxBvMMu6J8TWnjIWMgUzLkTj8G2JxFDGPhg&s",
          description: "Learn digital marketing strategies and tools for successful online marketing.",
          video: "https://www.youtube.com/digital-marketing-video",
        },
      ],
      Business: [], // Add more fields as needed
}